### ISSUE TITLE
Run notebooks on binder

### ISSUE THREAD

**Issue by johannes-fischer** [JuliaPluto/static-export-template#13]
Hi,
I was looking for a solution to share Pluto notebooks with students in a way that they can run them on binder. I was pointed here in https://github.com/fonsp/PlutoUtils.jl/issues/4.

However, when clicking "run on binder" in the static html export of your example notebook, loading it on binder always either fails with a crash or does not load even after long times.

Currently, I am using jupyter notebooks in binder, where I separated content and environment into two repos to not increase loading time of binder after changing the content, as described here: https://mybinder.readthedocs.io/en/latest/howto/external_binder_setup.html
So even if loading binder from the static html notebook worked, I am wondering if that separation between content and environment would be possible with this static export somehow.

I would prefer to be using Pluto over jupyter, due to its reactivity, but I haven't found a way to do so on binder.

**Comment by fonsp** [comment]
Hey @johannes-fischer ! It is currently not possible to generate a binder that is optimised for a set of Pluto notebooks, but this is something that we want to create in the future. Until then, it is probably not possible to use the combination of Pluto, binder, and the heavy packages that you need for your course material. The easiest solution might be to ask students to run the notebooks on their own computer, or to continue using Jupyter.

Thanks for the feedback!

**Comment by johannes-fischer** [comment]
Alright, thanks for the fast reply! It is great that you have this on your roadmap, though, I think that would be awesome!
