### ISSUE TITLE
Add comment about permissions to README

### ISSUE THREAD

**Issue by XQP-Munich** [JuliaPluto/static-export-template#15]
In order to get this to work, I had to change the permissions for the `GITHUB_TOKEN`, which is used in the CI, to allow the CI repository write access. Before the config change, it gave the error message

> Permission to [repo].git denied to github-actions[bot]

This is easy to do in the repository settings but it might still be worth mentioning in the README that users have to do this.

**Comment by pankgeorg** [comment]
Hello! Could you contribute a PR about this? Thanks!!
