### ISSUE TITLE
Where should I place a file to be included?

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaPluto/static-export-template#23]
Thanks a lot for creating this quite useful template! However, I have one question. Along with the example file, `My cool notebook.jl`, I created my own Pluto notebook, say, `lecture02.jl`. In my notebook, there is a line: `include("dst1u.jl")` and I already uploaded `dst1u.jl` on my GitHub repo in the same directory as `My cool notebook.jl` and `lecture02.jl` reside. Then, I followed all these instructions, and successfully created the website that has a link to `lecture02` as expected. When I pushed the link, however, it generated the following error at this `include("dst1u.jl")` statement:
```
SystemError: opening file "/home/runner/work/EACHABook/EACHABook/dst1u.jl": No such file or directory
```
I have two questions: 
1) My repo name is simply, `EACHABook`, but why this name is repeated twice in the above error message?
2) What should I use to append in the argument of `include("dst1u.jl")`? Should I write `include("/home/runner/EACHABook/EACHABook/dst1u.jl")`?
Thanks a lot for your help!!

**Comment by BoundaryValueProblems** [comment]
Actually, if I write `include(./dst1u.jl")` instead of the simple `include("dst1u.jl")`, it works! However, my question 1, i.e., why the repo name is repeated twice in the default file directory still remains.

**Comment by fonsp** [comment]
Hey @BoundaryValueProblems!

Happy that you found a solution! Honestly I am not sure why it doesn't work.

What I usually do with this is that I **copy-paste the contents of the included file into the notebook** in a hidden cell. That way, people who want to run my notebook don't need other files.

Another option is to put the `.jl` file online somehwere, like github or github gist, and then I get the perma-url of the raw file. 

E.g. for this file
https://github.com/JuliaPluto/featured/blob/main/src/puzzles-games/dither.jl
I get
https://raw.githubusercontent.com/JuliaPluto/featured/ae11aab65c3d190d29a591ecebedb59efecf691c/src/puzzles-games/dither.jl

You can then download that file in your notebook:

```julia
inlcude(download("https://raw.githubusercontent.com/JuliaPluto/featured/ae11aab65c3d190d29a591ecebedb59efecf691c/src/puzzles-games/dither.jl"))
```

And now the notebook will also work when you don't have the file in the same folder.
